headline_url_dict = {'Back_in_the_Building': 'https://venturewell.org/i-corps/llpvideos/customer-discovery/back-in-the-building/',
 'Before_Leaving_the_Building': 'https://venturewell.org/i-corps/llpvideos/customer-discovery/before-leaving-the-building/',
 'Channels': 'https://venturewell.org/i-corps/llpvideos/channels/',
 'Customer_Discovery': 'https://venturewell.org/i-corps/llpvideos/customer-discovery/',
 'Customer_Relationships': 'https://venturewell.org/i-corps/llpvideos/customer-relationships/',
 'Customer_Segments': 'https://venturewell.org/i-corps/llpvideos/customer-segments/',
 'Early_Mistakes_to_Avoid': 'https://venturewell.org/i-corps/llpvideos/customer-discovery/outside-the-building/early-mistakes-to-avoid/',
 'Final_Presentations': 'https://venturewell.org/i-corps/llpvideos/final-presentations/',
 'Final_Video': 'https://venturewell.org/i-corps/llpvideos/final-video/',
 'General_Discussion': 'https://venturewell.org/i-corps/llpvideos/general-discussion/',
 'Key_Activities_&amp;_Key_Resources': 'https://venturewell.org/i-corps/llpvideos/key-activities-key-resources/',
 'Key_Partners': 'https://venturewell.org/i-corps/llpvideos/key-partners/',
 'Mentor_Training': 'https://venturewell.org/i-corps/llpvideos/mentor-training/',
 'Revenue_Streams': 'https://venturewell.org/i-corps/llpvideos/revenue-streams/',
 'Rules_of_Customer_Interviews': 'https://venturewell.org/i-corps/llpvideos/customer-discovery/outside-the-building/rules-of-customer-interviews/',
 'Understanding_What_the_Customer_Is_Telling_You': 'https://venturewell.org/i-corps/llpvideos/customer-discovery/understanding-what-the-customer-is-telling-you/',
 'Value_Proposition': 'https://venturewell.org/i-corps/llpvideos/value-proposition/',
 'Getting_Your_Story_Straight_David_Riemer_on_Storytelling': 'https://venturewell.org/i-corps/llpvideos/david-riemer/'}

headline_url_dict_copy = {'Back_in_the_Building': [('Extracting Insight from Data',
                           'https://player.vimeo.com/video/125071868?title=0&#038;byline=0&#038;portrait=0'),
                          ('Pay Attention to Outliers',
                           'https://player.vimeo.com/video/125071813?title=0&#038;byline=0&#038;portrait=0'),
                          ('Getting the MVP Right',
                           'https://player.vimeo.com/video/125073155?title=0&#038;byline=0&#038;portrait=0'),
                          ('The “Other 85%”',
                           'https://player.vimeo.com/video/125072582?title=0&#038;byline=0&#038;portrait=0'),
                          ('Finding Early Evangelists',
                           'https://player.vimeo.com/video/123867302?title=0&#038;byline=0&#038;portrait=0'),
                          ('Communicating Your Discoveries',
                           'https://player.vimeo.com/video/125075291?title=0&#038;byline=0&#038;portrait=0')],
 'Before_Leaving_the_Building': [('Pre-Planning Contacts',
                                  'https://player.vimeo.com/video/125076430?title=0&#038;byline=0&#038;portrait=0'),
                                 ('Customer Interview Dry Runs',
                                  'https://player.vimeo.com/video/123749570?title=0&#038;byline=0&#038;portrait=0'),
                                 ('Discovery is for Founders',
                                  'https://player.vimeo.com/video/125073922?title=0&#038;byline=0&#038;portrait=0'),
                                 ('Pass/Fail Experiments',
                                  'https://player.vimeo.com/video/125074399?title=0&#038;byline=0&#038;portrait=0')],
 'Channels': [('Insights on: Channels – Week 3',
               'https://player.vimeo.com/video/125172686?title=0&#038;byline=0&#038;portrait=0'),
              ('Framing the Experiment',
               'https://player.vimeo.com/video/124044904?title=0&#038;byline=0&#038;portrait=0'),
              ('Distribution Channels: One Data Point Is Not a Test',
               'https://player.vimeo.com/video/124044860?title=0&#038;byline=0&#038;portrait=0')],
 'Customer_Discovery': [('“It Saved Us Several Years”',
                         'https://player.vimeo.com/video/125163503?title=0&#038;byline=0&#038;portrait=0'),
                        ('Stop Telling Yourself What You Want to Believe',
                         'https://player.vimeo.com/video/125172324?title=0&#038;byline=0&#038;portrait=0'),
                        ('Narrowing the Focus',
                         'https://player.vimeo.com/video/125172109?title=0&#038;byline=0&#038;portrait=0'),
                        ('Why PI’s and Founders Need to Get Out of the '
                         'Building',
                         'https://player.vimeo.com/video/125172326?title=0&#038;byline=0&#038;portrait=0'),
                        ('“This Was the Best Outcome”',
                         'https://player.vimeo.com/video/125172009?title=0&#038;byline=0&#038;portrait=0'),
                        ('Getting to the “Better Idea” Faster',
                         'https://player.vimeo.com/video/125174152?title=0&#038;byline=0&#038;portrait=0'),
                        ('Insights on: Does Customer Development Work in '
                         'Therapeutics?',
                         'https://player.vimeo.com/video/125173165?title=0&#038;byline=0&#038;portrait=0'),
                        ('The Phases of Customer Discovery',
                         'https://player.vimeo.com/video/123749569?title=0&#038;byline=0&#038;portrait=0')],
 'Customer_Relationships': [('Insights on: Customer Relationships – Week 4',
                             'https://player.vimeo.com/video/125171924?title=0&#038;byline=0&#038;portrait=0'),
                            ('Use Customers to Find More Customers',
                             'https://player.vimeo.com/video/124044854?title=0&#038;byline=0&#038;portrait=0'),
                            ('Customer Conversion',
                             'https://player.vimeo.com/video/68475355?title=0&amp;byline=0&amp;portrait=0')],
 'Customer_Segments': [('Insights on: Customer Segments – Week 2',
                        'https://player.vimeo.com/video/125172371?title=0&#038;byline=0&#038;portrait=0'),
                       ('Estimating Market Size',
                        'https://player.vimeo.com/video/124044813?title=0&#038;byline=0&#038;portrait=0'),
                       ('Customer Workflow',
                        'https://player.vimeo.com/video/124044831?title=0&#038;byline=0&#038;portrait=0'),
                       ('Customer Discovery / Customer Archetype',
                        'https://player.vimeo.com/video/126960119?title=0&#038;byline=0&#038;portrait=0'),
                       ('Customer Archetypes; Hypotheses &amp; Experiments',
                        'https://player.vimeo.com/video/126960191?title=0&#038;byline=0&#038;portrait=0'),
                       ('The Fog of Entrepreneurship',
                        'https://player.vimeo.com/video/124044956?title=0&#038;byline=0&#038;portrait=0'),
                       ('At the Start, All Your Stakeholders Are Customers',
                        'https://player.vimeo.com/video/124044950?title=0&#038;byline=0&#038;portrait=0'),
                       ('Square Pegs &amp; Round Holes – Mira Medicine',
                        'https://player.vimeo.com/video/125167603?title=0&#038;byline=0&#038;portrait=0')],
 'Early_Mistakes_to_Avoid': [('Death by PowerPoint',
                              'https://player.vimeo.com/video/125071455?title=0&#038;byline=0&#038;portrait=0'),
                             ('Death by Demo 1',
                              'https://player.vimeo.com/video/125071599?title=0&#038;byline=0&#038;portrait=0'),
                             ('Death by Demo 2',
                              'https://player.vimeo.com/video/123748881?title=0&#038;byline=0&#038;portrait=0'),
                             ('Understanding the Problem',
                              'https://player.vimeo.com/video/125071722?title=0&#038;byline=0&#038;portrait=0'),
                             ('Multi-Person Interview',
                              'https://player.vimeo.com/video/125071468?title=0&#038;byline=0&#038;portrait=0'),
                             ('Assuming You Know',
                              'https://player.vimeo.com/video/125071633?title=0&#038;byline=0&#038;portrait=0'),
                             ('B-to-B to C',
                              'https://player.vimeo.com/video/125072647?title=0&#038;byline=0&#038;portrait=0'),
                             ('Existing vs. New Markets',
                              'https://player.vimeo.com/video/125073376?title=0&#038;byline=0&#038;portrait=0'),
                             ('Asking the Right Question',
                              'https://player.vimeo.com/video/125073159?title=0&#038;byline=0&#038;portrait=0'),
                             ('Public Interviews',
                              'https://player.vimeo.com/video/125073099?title=0&#038;byline=0&#038;portrait=0')],
 'Final_Presentations': [('Knox: Final Presentation',
                          'https://player.vimeo.com/video/125175830?title=0&#038;byline=0&#038;portrait=0'),
                         ('Magnamosis: Final Presentation',
                          'https://player.vimeo.com/video/125176399?title=0&#038;byline=0&#038;portrait=0'),
                         ('Making Friends: Final Presentation',
                          'https://player.vimeo.com/video/125176324?title=0&#038;byline=0&#038;portrait=0'),
                         ('Mira Medicine: Final Presentation',
                          'https://player.vimeo.com/video/125176844?title=0&#038;byline=0&#038;portrait=0'),
                         ('ResultCare: Final Presentation',
                          'https://player.vimeo.com/video/127201327?title=0&#038;byline=0&#038;portrait=0'),
                         ('Tidepool.org: Final Presentation',
                          'https://player.vimeo.com/video/127201460?title=0&#038;byline=0&#038;portrait=0'),
                         ('Vitruvian Therapeutics: Final Presentation',
                          'https://player.vimeo.com/video/127201588?title=0&#038;byline=0&#038;portrait=0')],
 'Final_Video': [('Accelerated Medical Diagnostics: Final Video',
                  'https://player.vimeo.com/video/125174390?title=0&#038;byline=0&#038;portrait=0'),
                 ('Knox: Final Video',
                  'https://player.vimeo.com/video/125174351?title=0&#038;byline=0&#038;portrait=0'),
                 ('Magnamosis: Final Video',
                  'https://player.vimeo.com/video/125174556?title=0&#038;byline=0&#038;portrait=0'),
                 ('Making Friends: Final Video',
                  'https://player.vimeo.com/video/124045436?title=0&#038;byline=0&#038;portrait=0'),
                 ('Mira Medicine: Final Video',
                  'https://player.vimeo.com/video/125175826?title=0&#038;byline=0&#038;portrait=0'),
                 ('ResultCare: Final Video',
                  'https://player.vimeo.com/video/125176094?title=0&#038;byline=0&#038;portrait=0'),
                 ('Tidepool.org: Final Video',
                  'https://player.vimeo.com/video/125177148?title=0&#038;byline=0&#038;portrait=0'),
                 ('Vitruvian Therapeutics: Final Video',
                  'https://player.vimeo.com/video/125177052?title=0&#038;byline=0&#038;portrait=0')],
 'General_Discussion': [('How Large Will You Scale?',
                         'https://player.vimeo.com/video/126960122?title=0&#038;byline=0&#038;portrait=0'),
                        ('What If You’re a Visionary? – Risks &amp; Rewards',
                         'https://player.vimeo.com/video/125168406?title=0&#038;byline=0&#038;portrait=0'),
                        ('Your Startup: Do You Want to Spend 3 to 4 Years '
                         'Doing This?',
                         'https://player.vimeo.com/video/125173960?title=0&#038;byline=0&#038;portrait=0'),
                        ('Don’t Let the MVP Limit Your Vision',
                         'https://player.vimeo.com/video/68475350?title=0&amp;byline=0&amp;portrait=0')],
 'Getting_Your_Story_Straight_David_Riemer_on_Storytelling': [('Story '
                                                               'Narrative '
                                                               'and '
                                                               'Product '
                                                               'Narrative',
                                                               'https://player.vimeo.com/video/127203117?title=0&amp;byline=0&amp;portrait=0'),
                                                              ('Story '
                                                               '&amp; '
                                                               'Storytelling',
                                                               'https://player.vimeo.com/video/127201884?title=0&amp;byline=0&amp;portrait=0'),
                                                              ('The Power '
                                                               'of Story',
                                                               'https://player.vimeo.com/video/127202665'),
                                                              ('Story '
                                                               'Structure',
                                                               'https://player.vimeo.com/video/127263488?title=0&amp;byline=0&amp;portrait=0'),
                                                              ('The Main '
                                                               'Character',
                                                               'https://player.vimeo.com/video/127263873?title=0&amp;byline=0&amp;portrait=0'),
                                                              ('The Main '
                                                               'Conflict',
                                                               'https://player.vimeo.com/video/127264189?title=0&amp;byline=0&amp;portrait=0'),
                                                              ('Story '
                                                               'Challenges '
                                                               '&amp; '
                                                               'Solutions',
                                                               'https://player.vimeo.com/video/127263959?title=0&amp;byline=0&amp;portrait=0'),
                                                              ('Telling a '
                                                               'Great Story',
                                                               'https://player.vimeo.com/video/127264528?title=0&amp;byline=0&amp;portrait=0')],
 'Key_Activities_&amp;_Key_Resources': [('Insights on: Science Advisory '
                                         'Boards',
                                         'https://player.vimeo.com/video/125170233?title=0&#038;byline=0&#038;portrait=0'),
                                        ('Insights on: Resources, '
                                         'Activities &amp; Costs',
                                         'https://player.vimeo.com/video/125174183?title=0&#038;byline=0&#038;portrait=0'),
                                        ('No Laundry Lists. Just Facts!',
                                         'https://player.vimeo.com/video/124044944?title=0&#038;byline=0&#038;portrait=0')],
 'Key_Partners': [('Insights on: Key Partners – Week 6',
                   'https://player.vimeo.com/video/125175106?title=0&#038;byline=0&#038;portrait=0'),
                  ('Listen Carefully for Customer Discovery',
                   'https://player.vimeo.com/video/127201254?title=0&#038;byline=0&#038;portrait=0'),
                  ('The Timing of Partnerships',
                   'https://player.vimeo.com/video/68886210?title=0&amp;byline=0&amp;portrait=0')],
 'Mentor_Training': [('Lean Launchpad Mentor Training',
                      'https://player.vimeo.com/video/126943527?title=0&#038;byline=0&#038;portrait=0')],
 'Revenue_Streams': [('Value Based Pricing – “We Were Gobsmacked!”',
                      'https://player.vimeo.com/video/125173338?title=0&#038;byline=0&#038;portrait=0'),
                     ('Insights on: Revenue Streams – Week 5',
                      'https://player.vimeo.com/video/125173693?title=0&#038;byline=0&#038;portrait=0'),
                     ('The Importance of Experiments',
                      'https://player.vimeo.com/video/126960118?title=0&#038;byline=0&#038;portrait=0'),
                     ('Validating Product Pricing',
                      'https://player.vimeo.com/video/127201279?title=0&#038;byline=0&#038;portrait=0')],
 'Rules_of_Customer_Interviews': [('Being Aggressive',
                                   'https://player.vimeo.com/video/125073956?title=0&#038;byline=0&#038;portrait=0'),
                                  ('Conducting a Customer Interview',
                                   'https://player.vimeo.com/video/125074319?title=0&#038;byline=0&#038;portrait=0'),
                                  ('Letting the Customer Interview Flow',
                                   'https://player.vimeo.com/video/125074792?title=0&#038;byline=0&#038;portrait=0'),
                                  ('Sizing the Opportunity',
                                   'https://player.vimeo.com/video/125075924?title=0&#038;byline=0&#038;portrait=0'),
                                  ('Finding Patterns',
                                   'https://player.vimeo.com/video/125074929?title=0&#038;byline=0&#038;portrait=0'),
                                  ('Looking for Insights',
                                   'https://player.vimeo.com/video/123749575?title=0&#038;byline=0&#038;portrait=0')],
 'Understanding_What_the_Customer_Is_Telling_You': [('Engaging the Customer',
                                                     'https://player.vimeo.com/video/125072023?title=0&#038;byline=0&#038;portrait=0'),
                                                    ('Customer Empathy',
                                                     'https://player.vimeo.com/video/126960183?title=0&#038;byline=0&#038;portrait=0'),
                                                    ('The Distracted '
                                                     'Customer',
                                                     'https://player.vimeo.com/video/125073330?title=0&#038;byline=0&#038;portrait=0'),
                                                    ('Customers Lie',
                                                     'https://player.vimeo.com/video/125071593?title=0&#038;byline=0&#038;portrait=0'),
                                                    ('The User, the Buyer '
                                                     '&amp; the Saboteur',
                                                     'https://player.vimeo.com/video/125072036?title=0&#038;byline=0&#038;portrait=0')],
 'Value_Proposition': [('Pivoting…or Groping for a Business Model?',
                        'https://player.vimeo.com/video/124044890?title=0&#038;byline=0&#038;portrait=0'),
                       ('Seduced by Insufficient Data',
                        'https://player.vimeo.com/video/124044856?title=0&#038;byline=0&#038;portrait=0')]}